services:
  posts:
    image: lw89233/posts:latest
    container_name: posts-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTS_MICROSERVICE_PORT}:${POSTS_MICROSERVICE_PORT}"